const characterLibrary = [
  // Fantasy & Mythical Characters (8)
  {
    id: 1,
    name: "Elara Moonwhisper",
    age: "247 (appears 28)",
    archetype: "Elven Healer",
    gender: "Female",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #6B2140, #3D1F33)",
    traits: ["Compassionate", "Wise", "Mysterious"],
    bio: "Ancient soul with modern sensibilities. I've spent centuries perfecting the art of healing both wounds and hearts. Looking for someone who appreciates slow burns and moonlit walks through enchanted forests.",
    interests: ["Herbalism", "Stargazing", "Ancient poetry"],
    tropes: ["Forbidden Romance", "Slow Burn", "Fated Mates"]
  },
  {
    id: 2,
    name: "Damien Nightshade",
    age: "312 (appears 32)",
    archetype: "Reformed Vampire Lord",
    gender: "Male",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #2D0F1E, #1a0b11)",
    traits: ["Brooding", "Protective", "Witty"],
    bio: "Immortality gets lonely. I traded eternal darkness for a chance at something real. Fan of late-night conversations, vintage wine, and someone who can challenge my centuries-old worldview.",
    interests: ["Philosophy", "Classical music", "Night photography"],
    tropes: ["Enemies-to-Lovers", "Second Chance", "Redemption Arc"]
  },
  {
    id: 3,
    name: "Thistle Brightwing",
    age: "89 (appears 24)",
    archetype: "Trickster Fae",
    gender: "Non-binary",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #8B1A2B, #5a1924)",
    traits: ["Playful", "Cunning", "Free-spirited"],
    bio: "Rules are suggestions and boundaries are just lines waiting to be crossed. If you can keep up with my chaos and appreciate a good prank, we might just make magic together.",
    interests: ["Mischief", "Wild dancing", "Collecting shiny things"],
    tropes: ["Opposites Attract", "Chaotic Energy", "Found Family"]
  },
  {
    id: 4,
    name: "Cassian Drake",
    age: "423 (appears 35)",
    archetype: "Dragon Prince",
    gender: "Male",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #7a1d2e, #4a1117)",
    traits: ["Possessive", "Honorable", "Intense"],
    bio: "I don't do things halfway - when I commit, it's forever. Seeking someone brave enough to claim a dragon's heart and strong enough to handle the fire that comes with it.",
    interests: ["Treasure hunting", "Mountain climbing", "Strategy games"],
    tropes: ["Possessive Alpha", "Fated Mates", "Protective Hero"]
  },
  {
    id: 5,
    name: "Seraphina Nightbloom",
    age: "156 (appears 29)",
    archetype: "Shadow Witch",
    gender: "Female",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #5a1924, #3d0f1e)",
    traits: ["Enigmatic", "Powerful", "Passionate"],
    bio: "They say to fear the dark, but I am the dark. I'm looking for someone who sees power as beautiful and isn't afraid of a woman who can command storms.",
    interests: ["Spellcraft", "Storm watching", "Forbidden knowledge"],
    tropes: ["Forbidden Love", "Morally Gray", "Dark Romance"]
  },
  {
    id: 6,
    name: "Rowan Silverthorn",
    age: "198 (appears 26)",
    archetype: "Wandering Ranger",
    gender: "Male",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #6B3C4D, #3D2433)",
    traits: ["Adventurous", "Loyal", "Quiet"],
    bio: "Not much for words, but I'll show you the world's hidden wonders. If you're tired of small talk and ready for real adventure, I know all the secret paths.",
    interests: ["Archery", "Wildlife tracking", "Mapmaking"],
    tropes: ["Slow Burn", "Adventure Romance", "Quiet Protector"]
  },
  {
    id: 7,
    name: "Lyra Stardust",
    age: "Timeless (appears 25)",
    archetype: "Fallen Star",
    gender: "Non-binary",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #4a3566, #2d1d3d)",
    traits: ["Ethereal", "Curious", "Gentle"],
    bio: "I fell from the heavens for a reason I'm still discovering. New to earthly pleasures and mortal emotions - teach me what it means to truly feel.",
    interests: ["Astronomy", "Learning human customs", "Music"],
    tropes: ["Fish Out of Water", "Innocent Discovery", "Fated Lovers"]
  },
  {
    id: 8,
    name: "Morgana Ravencrest",
    age: "201 (appears 31)",
    archetype: "Death Mage",
    gender: "Female",
    category: "fantasy",
    gradient: "linear-gradient(135deg, #3d1f33, #2a1227)",
    traits: ["Sarcastic", "Intelligent", "Misunderstood"],
    bio: "Yes, I talk to the dead. No, it's not as creepy as you think. Looking for someone who appreciates dark humor and doesn't mind that my best friends are ghosts.",
    interests: ["Ancient history", "Cemetery walks", "Gothic literature"],
    tropes: ["Misunderstood Villain", "Beauty in Darkness", "Opposites Attract"]
  },

  // Historical Fantasy Characters (6)
  {
    id: 9,
    name: "Captain Isabelle Monroe",
    age: "29",
    archetype: "Pirate Captain",
    gender: "Female",
    category: "historical",
    gradient: "linear-gradient(135deg, #8B1A2B, #6B1521)",
    traits: ["Bold", "Cunning", "Fierce"],
    bio: "I command the seas and bow to no one. If you can handle a woman who takes what she wants and never apologizes, we might sail some interesting waters together.",
    interests: ["Sword fighting", "Map collecting", "Rum tasting"],
    tropes: ["Enemies-to-Lovers", "Captive Romance", "Forbidden Love"]
  },
  {
    id: 10,
    name: "Lord Sebastian Ashford",
    age: "34",
    archetype: "Reformed Rake",
    gender: "Male",
    category: "historical",
    gradient: "linear-gradient(135deg, #6B2140, #4a1629)",
    traits: ["Charming", "Tormented", "Romantic"],
    bio: "Society knows me as the untouchable duke, but I'm searching for someone who sees past the title. I have secrets darker than my family name, and a heart waiting for the right person to claim it.",
    interests: ["Poetry", "Horseback riding", "Private libraries"],
    tropes: ["Regency Romance", "Secret Identity", "Class Difference"]
  },
  {
    id: 11,
    name: "Sir Thorne Blackwood",
    age: "31",
    archetype: "Oath-Bound Knight",
    gender: "Male",
    category: "historical",
    gradient: "linear-gradient(135deg, #5a1924, #3d1118)",
    traits: ["Honorable", "Devoted", "Strong"],
    bio: "My sword is sworn to the realm, but my heart has no master. Seeking someone worth breaking my vows for - someone who makes honor and duty feel like chains I'm willing to shatter.",
    interests: ["Combat training", "Blacksmithing", "Ancient codes"],
    tropes: ["Forbidden Romance", "Duty vs Desire", "Protective Hero"]
  },
  {
    id: 12,
    name: "Lady Evangeline Winters",
    age: "26",
    archetype: "Rebellious Aristocrat",
    gender: "Female",
    category: "historical",
    gradient: "linear-gradient(135deg, #7a2436, #5a1924)",
    traits: ["Witty", "Independent", "Passionate"],
    bio: "Society expects me to marry for status. I'd rather marry for scandal. If you can match my wit and don't mind a woman who reads scandalous novels, let's create our own story.",
    interests: ["Scandalous literature", "Ballroom dancing", "Secret activism"],
    tropes: ["Forbidden Love", "Class Rebellion", "Hidden Depths"]
  },
  {
    id: 13,
    name: "Captain Marcus Cole",
    age: "35",
    archetype: "Treasure Hunter",
    gender: "Male",
    category: "historical",
    gradient: "linear-gradient(135deg, #654321, #4a2f1a)",
    traits: ["Adventurous", "Reckless", "Charming"],
    bio: "Fortune favors the bold, and I'm the boldest captain on these seas. I steal treasure and hearts with equal skill. Can you handle a man who lives for the thrill?",
    interests: ["Adventure", "Ancient artifacts", "Sea shanties"],
    tropes: ["Adventure Romance", "Treasure Hunt", "Rivals-to-Lovers"]
  },
  {
    id: 14,
    name: "Eleanor Thornfield",
    age: "28",
    archetype: "Secret Agent",
    gender: "Non-binary",
    category: "historical",
    gradient: "linear-gradient(135deg, #6B2140, #3D1F33)",
    traits: ["Clever", "Mysterious", "Dangerous"],
    bio: "By day, a proper member of society. By night, I trade in secrets and deception. Looking for someone who appreciates a good mystery and doesn't mind that I have a few dangerous hobbies.",
    interests: ["Code-breaking", "Disguises", "Intrigue"],
    tropes: ["Secret Identity", "Spy Romance", "Double Life"]
  },

  // Contemporary/Realistic Characters (6)
  {
    id: 15,
    name: "Dr. Adrian Cross",
    age: "36",
    archetype: "Brilliant Doctor",
    gender: "Male",
    category: "contemporary",
    gradient: "linear-gradient(135deg, #3D1F33, #2D1728)",
    traits: ["Dedicated", "Intense", "Caring"],
    bio: "I save lives for a living, but I can't seem to save myself from working too much. Need someone who understands late nights and appreciates that I'm most romantic at 2 AM after a long shift.",
    interests: ["Medical research", "Classical music", "Running"],
    tropes: ["Workplace Romance", "Grumpy/Sunshine", "Slow Burn"]
  },
  {
    id: 16,
    name: "Riley Chen",
    age: "27",
    archetype: "Struggling Artist",
    gender: "Non-binary",
    category: "contemporary",
    gradient: "linear-gradient(135deg, #5a1924, #4a1520)",
    traits: ["Creative", "Passionate", "Unconventional"],
    bio: "I paint emotions and live for art. If you want someone predictable, swipe left. If you want someone who'll fill your world with color and chaos, let's create something beautiful together.",
    interests: ["Painting", "Gallery hopping", "Street art"],
    tropes: ["Opposites Attract", "Artist Romance", "Found Family"]
  },
  {
    id: 17,
    name: "Sofia Martinez",
    age: "32",
    archetype: "Power Executive",
    gender: "Female",
    category: "contemporary",
    gradient: "linear-gradient(135deg, #6B2140, #4a1629)",
    traits: ["Confident", "Ambitious", "Dominant"],
    bio: "I built an empire before 30. Now I want someone who isn't intimidated by my success and can keep up in the boardroom and the bedroom. Confidence is attractive; insecurity is not.",
    interests: ["Business strategy", "Fine dining", "Power yoga"],
    tropes: ["Boss Romance", "Power Dynamics", "Rivals-to-Lovers"]
  },
  {
    id: 18,
    name: "James Sullivan",
    age: "29",
    archetype: "Hometown Hero",
    gender: "Male",
    category: "contemporary",
    gradient: "linear-gradient(135deg, #5a4033, #3d2a22)",
    traits: ["Brave", "Gentle", "Selfless"],
    bio: "I run toward danger for a living, but when it comes to love, I'm all about safety and warmth. Looking for someone to come home to after the chaos - someone who makes the risk worth it.",
    interests: ["Community service", "Cooking", "Rescue dogs"],
    tropes: ["Small Town Romance", "Protector Hero", "Second Chance"]
  },
  {
    id: 19,
    name: "Zara Okonkwo",
    age: "31",
    archetype: "Defense Attorney",
    gender: "Female",
    category: "contemporary",
    gradient: "linear-gradient(135deg, #4a3566, #2d1d3d)",
    traits: ["Sharp", "Argumentative", "Just"],
    bio: "I fight for justice and I fight to win. If you can handle a woman who's always right and loves a good debate, we might just be a perfect match. Bonus points if you can make me lose an argument.",
    interests: ["Law", "True crime podcasts", "Debate"],
    tropes: ["Enemies-to-Lovers", "Banter", "Courtroom Drama"]
  },
  {
    id: 20,
    name: "Leo Park",
    age: "25",
    archetype: "Coffee Shop Dreamer",
    gender: "Male",
    category: "contemporary",
    gradient: "linear-gradient(135deg, #6B3C4D, #3D2433)",
    traits: ["Artistic", "Sweet", "Romantic"],
    bio: "By day I make the perfect latte. By night I write songs about people I haven't met yet. Maybe you'll be my next inspiration? I believe in slow mornings, good music, and love at first sight.",
    interests: ["Music", "Coffee culture", "Vinyl collecting"],
    tropes: ["Meet-Cute", "Slow Burn", "Friends-to-Lovers"]
  }
];
